name: Docker Image Build and Push - Ubuntu

on:
  push:
    branches:
      - master
    tags:
      - "*.*.*"
  pull_request:

jobs:

  build-push:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Git Metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            akito13/userdef
          flavor: |
            latest=true
            prefix=
            suffix=
          tags: |
            type=raw,value=libc
            type=raw,value=ubuntu
            type=schedule,pattern={{date 'YYYYMMDD'}}-ubuntu
            type=semver,pattern={{version}}-ubuntu
            type=semver,pattern={{major}}.{{minor}}-ubuntu
            type=semver,pattern={{major}}-ubuntu
            type=sha,prefix=,format=long
            type=sha,prefix=,format=short

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: |
            image=moby/buildkit:v0.12.0
          buildkitd-flags: --debug

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./libc.Dockerfile
          platforms: linux/ppc64le,linux/arm/v7,linux/arm64/v8,linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
